name: Check formatting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  fmt:
    name: Cargo fmt lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: Swatinem/rust-cache@v2

      - name: Run fmt lint
        run: cargo fmt --all -- --check

  clippy:
    name: Cargo clippy lint
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: Swatinem/rust-cache@v2

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn
          cache-dependency-path: 'Ecdar-GUI-Web/yarn.lock'

      - name: Install yarn dependencies
        run: cd Ecdar-GUI-Web && yarn install

      - name: Run clippy lint
        run: cargo clippy --all-targets -- -D warnings
